import Head from "next/head";
import Markdown from "@/components/Markdown";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Markdown Previewer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Markdown />
    </div>
  );
}
